/** API path segments (relative to /api) */
export const endpoints = {
  checkToken: '/check-token',
  dangNhap: '/dang-nhap',
  dangXuat: '/dang-xuat',
  loginGoogle: '/login-google',
  quenMatKhau: '/quen-mat-khau',
  datLaiMatKhau: '/dat-lai-mat-khau',
  profile: '/profile',
  profileUpdate: '/profile/update',
  profileAvatar: '/profile/update-avatar',
  profilePassword: '/profile/change-password',
  cauHinhFooter: '/cau-hinh/footer/data',
  cauHinhThongBao: '/cau-hinh/thong-bao',
  cauHinhChung: '/admin/cau-hinh/chung/data',
  leaderboard: '/leaderboard',
  baiHoc: '/bai-hoc',
  danhMucBaiHoc: '/danh-muc-bai-hoc',
  broadcastingAuth: '/broadcasting/auth',
  ttsVietnamese: '/tts/vietnamese',
  chat: {
    systemSession: '/chat/system/session',
    systemHistory: '/chat/system/history',
    systemGreeting: '/chat/system/greeting',
    system: '/chat/system',
    studentSession: '/student/chat/session',
    studentSessions: '/student/chat/sessions',
    teacherSessions: '/teacher/chat/sessions',
    teacherUnread: '/teacher/chat/unread-count',
  },
  admin: {
    phanQuyen: '/admin/phan-quyen/data',
    phanQuyenDongBo: '/admin/phan-quyen/dong-bo',
    vaiTroCreate: '/admin/vai-tro/create',
    quanLyTaiKhoan: '/admin/quan-ly-tai-khoan',
    kiemDuyet: '/admin/kiem-duyet-bai-hoc',
    danhMucBaiHoc: '/admin/danh-muc-bai-hoc',
  },
};
